import { Inter } from "next/font/google";
import "./globals.css";
import Services from "./services/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </head> 
      <body className={`${inter.className} bg-black min-h-screen flex justify-center items-center relative overflow-hidden`}>
      <Services/>
        {children}
      </body>
    </html>
  );
}
